# Generated by Django 6.1 on 2026-08-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, help_text='Se usa como nombre de usuario para iniciar sesión.', max_length=12, null=True, unique=True, verbose_name='RUT sin dígito verificador'),
        ),
    ]
