# Generated by Django 6.1 on 2026-08-18 19:51

from django.db import migrations, models


def mark_existing_staff_as_admin(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(is_staff=True).update(role='ADMIN')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USUARIO', 'Usuario'), ('TI', 'TI'), ('ADMIN', 'Administrador')], default='USUARIO', max_length=10, verbose_name='Rol'),
        ),
        migrations.RunPython(mark_existing_staff_as_admin, migrations.RunPython.noop),
    ]
