# Generated by Django 6.1 on 2026-08-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_dismissed',
            field=models.BooleanField(default=False, verbose_name='No mostrar guía inicial'),
        ),
    ]
