# Generated by Django 6.1 on 2026-08-19 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_fix_legacy_response_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoomCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50, verbose_name='Sala')),
                ('review_date', models.DateField(auto_now_add=True, verbose_name='Fecha de revisión')),
                ('hdmi', models.BooleanField(default=False, verbose_name='HDMI')),
                ('wifi_tv', models.BooleanField(default=False, verbose_name='Wi‑Fi en televisión')),
                ('projector_wifi', models.BooleanField(default=False, verbose_name='Proyección Wi‑Fi')),
                ('webcam', models.BooleanField(default=False, verbose_name='Cámara web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Checkeo de sala',
                'verbose_name_plural': 'Checkeos de salas',
                'unique_together': {('room_name', 'review_date')},
            },
        ),
    ]
